In [2]:
import numpy as np

In [2]:
A = np.array([
    [1, -1 , 2],
    [3, 2, 2], 
    [4, 1, 2], 
    [7, 5, 6]
])
A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2],
       [ 7,  5,  6]])

In [4]:
B = np.array([
    [0, 1], 
    [-1, 3], 
    [5, 2]
])
B

array([[ 0,  1],
       [-1,  3],
       [ 5,  2]])

In [5]:
C = np.random.rand(3, 5)

array([[0.20113022, 0.54288952, 0.24307198, 0.45813479, 0.64387165],
       [0.55765454, 0.73003153, 0.58749877, 0.33367469, 0.93243762],
       [0.54403612, 0.38963453, 0.00603929, 0.67140204, 0.147982  ]])

In [9]:
D = np.zeros((2, 4))
D

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2],
       [ 7,  5,  6]])

In [12]:
A[0][2]

2

In [14]:
A = np.array([
    [1, -1 , 2],
    [3, 2, 2], 
    [4, 1, 2]
])
B = np.random.rand(3, 3)

In [15]:
A+B

array([[ 1.4717307 , -0.50265291,  2.73460066],
       [ 3.21163467,  2.63805828,  2.25420119],
       [ 4.97733153,  1.24723124,  2.33862107]])

In [16]:
5*A

array([[ 5, -5, 10],
       [15, 10, 10],
       [20,  5, 10]])

In [17]:
np.dot(A, B)

array([[2.21475908, 0.35375129, 1.15764161],
       [3.79312447, 3.26262032, 3.3894465 ],
       [4.0532205 , 3.12190913, 3.86984597]])

In [18]:
A @ B

array([[2.21475908, 0.35375129, 1.15764161],
       [3.79312447, 3.26262032, 3.3894465 ],
       [4.0532205 , 3.12190913, 3.86984597]])

In [19]:
A @ B + (A + 2 * B)

array([[ 4.15822047,  0.34844547,  4.62684293],
       [ 7.21639381,  6.53873689,  5.89784888],
       [10.00788355,  4.61637162,  6.54708811]])

In [25]:
A = np.array([
    [1, -1 , 2],
    [3, 2, 2], 
    [4, 1, 2]
])

In [21]:
A_transpose = np.transpose(A)
A_transpose

array([[ 1,  3,  4],
       [-1,  2,  1],
       [ 2,  2,  2]])

In [22]:
A.T

array([[ 1,  3,  4],
       [-1,  2,  1],
       [ 2,  2,  2]])

In [23]:
I = np.identity(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
A @ I

array([[ 1., -1.,  2.],
       [ 3.,  2.,  2.],
       [ 4.,  1.,  2.]])

In [29]:
A_inverse  = np.linalg.pinv(A)
A_inverse

array([[-0.2, -0.4,  0.6],
       [-0.2,  0.6, -0.4],
       [ 0.5,  0.5, -0.5]])

In [30]:
A_inverse @ A

array([[ 1.00000000e+00, -3.33066907e-16, -2.22044605e-16],
       [ 4.44089210e-16,  1.00000000e+00,  0.00000000e+00],
       [-8.88178420e-16,  1.11022302e-16,  1.00000000e+00]])

In [6]:
house_size = np.array([0.9, 1.4, 2, 2.1, 2.6, 3.3, 3.35, 3.9, 4.4, 4.7, 5.2, 5.75, 6.7, 6.9])
house_size
house_price = np.array([0.3, 0.75, 0.45, 1.1, 1.45, 0.9, 1.8, 0.9, 1.5, 2.2, 1.75, 2.3, 2.49, 2.6])

In [7]:
house_size * house_price

array([ 0.27 ,  1.05 ,  0.9  ,  2.31 ,  3.77 ,  2.97 ,  6.03 ,  3.51 ,
        6.6  , 10.34 ,  9.1  , 13.225, 16.683, 17.94 ])

In [1]:
for layer in range(3, 0, -1):
    print(layer)

3
2
1


In [2]:
for i in range(1, 4):
    print(i)

1
2
3
