In [1]:
import numpy as np

In [2]:
A = np.array([
    [1, -1 , 2],
    [3, 2, 2], 
    [4, 1, 2], 
    [7, 5, 6]
])
A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2],
       [ 7,  5,  6]])

In [4]:
B = np.array([
    [0, 1], 
    [-1, 3], 
    [5, 2]
])
B

array([[ 0,  1],
       [-1,  3],
       [ 5,  2]])

In [5]:
C = np.random.rand(3, 5)

array([[0.20113022, 0.54288952, 0.24307198, 0.45813479, 0.64387165],
       [0.55765454, 0.73003153, 0.58749877, 0.33367469, 0.93243762],
       [0.54403612, 0.38963453, 0.00603929, 0.67140204, 0.147982  ]])

In [9]:
D = np.zeros((2, 4))
D

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2],
       [ 7,  5,  6]])

In [12]:
A[0][2]

2